zeebe:
  initContainers:
    - name: init-exporter-job-worker
      image: curlimages/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["curl -L https://camunda.jfrog.io/artifactory/camunda-bpm-community-extensions/org/camunda/community/extension/zeebe/exporter/jobworker/zeebe-embedded-job-worker/0.0.10/zeebe-embedded-job-worker-0.0.10.jar -o /exporters/zeebe-embedded-job-worker-0.0.10.jar; ls -al /exporters"]
      securityContext:
        runAsUser: 1001
        runAsNonRoot: true
      volumeMounts:
      - name: exporters
        mountPath: /exporters/
  extraVolumes:
    - name: exporters-writable
      emptyDir: {}
  extraVolumeMounts:
    - name: exporters-writable
      mountPath: /usr/local/zeebe/exporters/
  env:
    - name: ZEEBE_BROKER_EXPORTERS_JOBWORKER_JARPATH
      value: "exporters/zeebe-embedded-job-worker-0.0.10.jar"
    - name: ZEEBE_BROKER_EXPORTERS_JOBWORKER_CLASSNAME
      value: org.camunda.community.extension.zeebe.exporter.jobworker.EmbeddedJobWorker
